# -*- coding: utf-8 -*-
"""
Monte Carlo simulator for West Bengal election sensitivity analysis.

This version assumes baseline_predictions.csv has already been generated by
baseline_prediction_v3.py, where SIR adjustment and Lok Sabha swing have already
been applied to produce:

    pred_tmc_vote_share
    pred_bjp_vote_share
    pred_left_vote_share
    pred_congress_vote_share
    pred_others_vote_share

Monte Carlo is therefore applied around these predicted vote shares directly.
It does NOT apply SIR again.
"""

from pathlib import Path
import numpy as np
import pandas as pd


PARTIES = ["tmc", "bjp", "left", "congress", "others"]
PARTY_LABELS = [p.upper() for p in PARTIES]


def get_vote_cols(prefix="pred"):
    return [f"{prefix}_{p}_vote_share" for p in PARTIES]


def normalize_vote_shares(df, vote_cols):
    """Clip negative vote shares and normalize each row to 100."""
    df = df.copy()
    df[vote_cols] = df[vote_cols].clip(lower=0)
    row_sum = df[vote_cols].sum(axis=1)

    df[vote_cols] = np.where(
        row_sum.to_numpy()[:, None] > 0,
        df[vote_cols].div(row_sum, axis=0) * 100,
        np.nan,
    )

    return df


def calculate_winner_and_margin(df, vote_cols, prefix):
    """Calculate winner and top-two margin from vote-share columns."""
    df = df.copy()

    df[f"{prefix}_winner"] = (
        df[vote_cols]
        .idxmax(axis=1)
        .str.replace("pred_", "", regex=False)
        .str.replace("sim_", "", regex=False)
        .str.replace("_vote_share", "", regex=False)
        .str.upper()
    )

    sorted_votes = np.sort(df[vote_cols].to_numpy(), axis=1)
    df[f"{prefix}_margin_pct"] = sorted_votes[:, -1] - sorted_votes[:, -2]

    return df


def get_margin_scaled_noise(df, rng, base_sd=1.0, margin_col="sir_adjusted_margin_pct"):
    """
    Local constituency noise scaled by margin.

    Close seats receive more local noise; safer seats receive less.
    """
    if margin_col not in df.columns:
        margin_col = "baseline_margin_pct"

    margin = df[margin_col]

    noise_scale = np.select(
        [
            margin < 1,
            margin < 3,
            margin < 5,
            margin < 10,
        ],
        [
            1.00,  # extremely close
            0.70,  # close
            0.40,  # competitive
            0.20,  # moderately safe
        ],
        default=0.10,  # safe seats
    )

    return rng.normal(0, base_sd, size=len(df)) * noise_scale


def prepare_baseline(df):
    """
    Ensure predicted vote shares are normalized and baseline winner/margin exist.
    """
    df = df.copy()
    pred_cols = get_vote_cols("pred")

    missing = [c for c in pred_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required predicted vote-share columns: {missing}")

    df = normalize_vote_shares(df, pred_cols)

    df = calculate_winner_and_margin(
        df,
        vote_cols=pred_cols,
        prefix="sir_adjusted",
    )

    return df


def simulate_one_election(
    df,
    statewide_sd=1.0,
    constituency_sd=1.0,
    statewide_clip=2.0,
    local_clip=2.5,
    random_state=None,
):
    """
    Simulate one election around SIR-adjusted predicted vote shares.

    Uses:
    - party-specific statewide shocks
    - margin-scaled constituency-level local shocks
    """
    rng = np.random.default_rng(random_state)
    sim = df.copy()

    pred_cols = get_vote_cols("pred")
    sim_cols = get_vote_cols("sim")

    # Start simulation columns from predicted baseline columns
    for pred_col, sim_col in zip(pred_cols, sim_cols):
        sim[sim_col] = sim[pred_col]

    # Party-specific statewide shocks
    statewide_shocks = {
        p: np.clip(rng.normal(0, statewide_sd), -statewide_clip, statewide_clip)
        for p in PARTIES
    }

    for p in PARTIES:
        sim_col = f"sim_{p}_vote_share"

        local_noise = get_margin_scaled_noise(
            sim,
            rng,
            base_sd=constituency_sd,
            margin_col="sir_adjusted_margin_pct",
        )
        local_noise = np.clip(local_noise, -local_clip, local_clip)

        sim[sim_col] = sim[sim_col] + statewide_shocks[p] + local_noise

    sim = normalize_vote_shares(sim, sim_cols)

    sim = calculate_winner_and_margin(
        sim,
        vote_cols=sim_cols,
        prefix="mc",
    )

    return sim[["district", "constituency", "mc_winner", "mc_margin_pct"]]


def run_monte_carlo(
    df,
    n_simulations=10000,
    statewide_sd=1.0,
    constituency_sd=1.0,
    random_seed=42,
):
    """
    Run many simulated elections.

    Returns
    -------
    seat_distribution:
        One row per simulation with party seat counts.
    win_probability:
        Constituency-level win probability by party.
    """
    rng = np.random.default_rng(random_seed)

    seat_rows = []
    winner_rows = []

    for sim_id in range(n_simulations):
        sim = simulate_one_election(
            df,
            statewide_sd=statewide_sd,
            constituency_sd=constituency_sd,
            random_state=rng.integers(0, 1_000_000_000),
        )

        seat_count = sim["mc_winner"].value_counts().to_dict()
        seat_count["simulation"] = sim_id
        seat_rows.append(seat_count)

        temp = sim[["district", "constituency", "mc_winner"]].copy()
        temp["simulation"] = sim_id
        winner_rows.append(temp)

    seat_distribution = pd.DataFrame(seat_rows).fillna(0)

    for p in PARTY_LABELS:
        if p not in seat_distribution.columns:
            seat_distribution[p] = 0

    seat_distribution[PARTY_LABELS] = seat_distribution[PARTY_LABELS].astype(int)
    seat_distribution["total_seats"] = seat_distribution[PARTY_LABELS].sum(axis=1)

    all_winners = pd.concat(winner_rows, ignore_index=True)

    win_probability = (
        all_winners
        .groupby(["district", "constituency", "mc_winner"])
        .size()
        .reset_index(name="wins")
    )
    win_probability["win_probability"] = win_probability["wins"] / n_simulations

    win_probability = win_probability.sort_values(
        ["district", "constituency", "win_probability"],
        ascending=[True, True, False],
    )

    return seat_distribution, win_probability


def summarize_seat_distribution(seat_distribution):
    """Summarize seat distribution by party."""
    rows = []

    for p in PARTY_LABELS:
        rows.append({
            "party": p,
            "mean_seats": seat_distribution[p].mean(),
            "median_seats": seat_distribution[p].median(),
            "p05": seat_distribution[p].quantile(0.05),
            "p10": seat_distribution[p].quantile(0.10),
            "p90": seat_distribution[p].quantile(0.90),
            "p95": seat_distribution[p].quantile(0.95),
            "min": seat_distribution[p].min(),
            "max": seat_distribution[p].max(),
        })

    return pd.DataFrame(rows)


def add_uncertainty_to_constituencies(df, win_probability):
    """
    Attach Monte Carlo win probability of deterministic SIR-adjusted winner.
    """
    df = df.copy()

    winner_prob = win_probability.rename(
        columns={
            "mc_winner": "sir_adjusted_winner",
            "win_probability": "sir_adjusted_win_probability",
        }
    )

    df = df.merge(
        winner_prob[[
            "district",
            "constituency",
            "sir_adjusted_winner",
            "sir_adjusted_win_probability",
        ]],
        on=["district", "constituency", "sir_adjusted_winner"],
        how="left",
    )

    df["uncertainty_class"] = pd.cut(
        df["sir_adjusted_win_probability"],
        bins=[0, 0.55, 0.70, 0.85, 1.00],
        labels=["Toss-up", "Lean", "Likely", "Safe"],
        include_lowest=True,
    )

    return df


def main():
    processed_dir = Path("data/processed")
    input_path = processed_dir / "baseline_predictions.csv"

    df = pd.read_csv(input_path)

    df = prepare_baseline(df)

    deterministic_counts = df["sir_adjusted_winner"].value_counts()
    print("\nDeterministic SIR-adjusted baseline:")
    print(deterministic_counts)

    seat_distribution, win_probability = run_monte_carlo(
        df,
        n_simulations=10000,
        statewide_sd=1.0,
        constituency_sd=1.0,
        random_seed=42,
    )

    # Sanity check: every simulation should have 294 seats
    if not seat_distribution["total_seats"].eq(len(df)).all():
        raise ValueError(
            "Some simulations do not sum to the number of constituencies. "
            "Check duplicate or missing constituency rows."
        )

    seat_summary = summarize_seat_distribution(seat_distribution)
    constituency_uncertainty = add_uncertainty_to_constituencies(df, win_probability)

    seat_distribution.to_csv(processed_dir / "mc_seat_distribution.csv", index=False)
    seat_summary.to_csv(processed_dir / "mc_seat_summary.csv", index=False)
    win_probability.to_csv(processed_dir / "mc_constituency_win_probability.csv", index=False)
    constituency_uncertainty.to_csv(
        processed_dir / "constituency_uncertainty.csv",
        index=False,
    )

    print("\nMonte Carlo seat summary:")
    print(seat_summary)

    print("\nUncertainty classes:")
    print(constituency_uncertainty["uncertainty_class"].value_counts())

    print("\nSaved:")
    print(" - data/processed/mc_seat_distribution.csv")
    print(" - data/processed/mc_seat_summary.csv")
    print(" - data/processed/mc_constituency_win_probability.csv")
    print(" - data/processed/constituency_uncertainty.csv")


if __name__ == "__main__":
    main()
